### ISSUE TITLE
Can't find the installation file

### ISSUE THREAD

**Issue by SarahAl98** [silnrsi/font-scheherazade#10]
Hello everyone
I can't find the installation file when I download the packet. There is no TTF or OTF file.
I hope someone can help me.

**Comment by n7s** [comment]
The font files are in the zip file in the release section on https://github.com/silnrsi/font-scheherazade/releases

**Comment by LornaSIL** [comment]
Hi @SarahAl98 You may download a zip file from here: https://github.com/silnrsi/font-scheherazade/releases/download/v4.000/ScheherazadeNew-4.000.zip

or the official site is: https://software.sil.org/scheherazade/download/

Download the .zip file, unzip it. Install the ttf files per your operating system. We do not provide installers, just the zip.

**Comment by SarahAl98** [comment]
When I unzip the file there is no ttf file. That is why I am a bit confused.
Maybe someone can help me find it.

**Comment by SarahAl98** [comment]
> Hi @SarahAl98 You may download a zip file from here: https://github.com/silnrsi/font-scheherazade/releases/download/v4.000/ScheherazadeNew-4.000.zip
> 
> or the official site is: https://software.sil.org/scheherazade/download/
> 
> Download the .zip file, unzip it. Install the ttf files per your operating system. We do not provide installers, just the zip.

I can't find the ttf files in the zip file after unzipping it. And it's the same no matter where I download it.

**Comment by jvgaultney** [comment]
I have verified that the .ttf files are included in the .zip download from the URL Lorna provided. You may want to try using a different decompression utility to decompress the .zip file.

**Comment by SarahAl98** [comment]
> I have verified that the .ttf files are included in the .zip download from the URL Lorna provided. You may want to try using a different decompression utility to decompress the .zip file.

Thank you so much. I still seem to have problems. These are the files that appear after extracting.
<img width="445" alt="Screenshot 2024-01-03 155018" src="https://github.com/silnrsi/font-scheherazade/assets/155474165/69429239-eeda-4113-8518-6737490a4067">

**Comment by jvgaultney** [comment]
The files are there - the four ones starting with Sch*. Your operating system is hiding the .ttf extension.

**Comment by SarahAl98** [comment]
> The files are there - the four ones starting with Sch*. Your operating system is hiding the .ttf extension.

Thank you so much
