### ISSUE TITLE
Missing characters when used with `python-arabic-reshaper`

### ISSUE THREAD

**Issue by WissamAntoun** [silnrsi/font-scheherazade#2]
Hey,

Bug description: When rendering arabic characters using the `python-arabic-reshaper` and `bidi.get_display()` I get the following output using this code:

```python
from PIL import Image, ImageDraw, ImageFont
from arabic_reshaper import ArabicReshaper
from bidi.algorithm import get_display

configuration = {
    'delete_harakat': False,
    'support_ligatures': True,
    'shift_harakat_position ': True,
    'use_unshaped_instead_of_isolated': True,
    'support_zwj': False
}
reshaper = ArabicReshaper(configuration=configuration)

W, H = (300, 100) # image size
background = (255,255,255) # white
fontsize = 40
font = ImageFont.truetype("/content/ScheherazadeNew-3.100/ScheherazadeNew-Regular.ttf", fontsize)

image = Image.new('RGBA', (W, H), background)
draw = ImageDraw.Draw(image)
text_to_be_reshaped = "اليوم wissam"
reshaped_text = reshaper.reshape(text_to_be_reshaped)
bidi_text = get_display(reshaped_text)
w, h = font.getsize(bidi_text)
draw.text(((W-w)/2,(H-h)/2), bidi_text, fill='black', font=font)
image.show()
```

![image](https://user-images.githubusercontent.com/44616226/122639169-f37a0f00-d100-11eb-932e-2a7c56f29c17.png)

It seems that the arabic reshaper is using the Arabic Presentation Forms-B, which is missing from the Scheherazade font. I tried fixing it by manually adding characters using FontForge for characters in the range `U+FE80` -> `U+FEFC`.
It seems to fix the issue for most characters, except for the equivalent Presentation Forms-B of `uni064A.noDots.medi` and `.init`.

I'm not sure how to fix this since these 2 characters aren't present in the `Arabic Presentation Forms-B`.

P.S.: I'm very new to font field

Thanks for the help

**Comment by bobh0303** [comment]
Any software that depends on the Arabic Presentation Forms will be severely limited because many of the Arabic characters do not have presentation forms encoded in Unicode. A few examples of the 161 that I count:

```
063B ARABIC LETTER KEHEH WITH TWO DOTS ABOVE is missing init, med, fin
063C ARABIC LETTER KEHEH WITH THREE DOTS BELOW is missing init, med, fin
063D ARABIC LETTER FARSI YEH WITH INVERTED V is missing init, med, fin
063E ARABIC LETTER FARSI YEH WITH TWO DOTS ABOVE is missing init, med, fin
063F ARABIC LETTER FARSI YEH WITH THREE DOTS ABOVE is missing init, med, fin
066E ARABIC LETTER DOTLESS BEH is missing init, med, fin
066F ARABIC LETTER DOTLESS QAF is missing init, med, fin
068F ARABIC LETTER DAL WITH THREE DOTS ABOVE DOWNWARDS is missing fin
0690 ARABIC LETTER DAL WITH FOUR DOTS ABOVE is missing fin
0692 ARABIC LETTER REH WITH SMALL V is missing fin
0693 ARABIC LETTER REH WITH RING is missing fin
...
```

Because of this limitation, we discourage use of any of the Arabic Presentation form characters. For rendering, it is better to use software such as Harfbuzz that utilizes the OpenType code within the font.

**Comment by khaledhosny** [comment]
FWIW, Pillow supports proper shaping if Raqm support is available, no need for using presentation forms.

**Comment by WissamAntoun** [comment]
Yeah that's it, It worked fine when I installed Raqm. Thank you
