### ISSUE TITLE
Refining `«»`

### ISSUE THREAD

**Issue by mr-islam** [silnrsi/font-scheherazade#5]
Hi, I'm really loving Scheherazade New and congratulate you all on this milestone!

I just had a small request: is there any plan to refine the design for `«` and `»` characters? It is very regularly used in Arabic books and papers as quotation marks. 

Currently, they display as the following in Scheherazade New:
![image](https://user-images.githubusercontent.com/17675428/146003492-34f0e65b-636b-4b34-9799-fbd7b32aa5b4.png)

The above is functional, but this design with a sharp, acute angle is not usually used in Arabic texts. Rather, they use a more curvy and gentle style, making it less jarring to read and feel less foreign:
![image](https://user-images.githubusercontent.com/17675428/146003672-062710ec-9453-40f1-bce8-5089d8d3da9e.png)

(This example is from the [Kitab font](https://github.com/quranacademy/kitab-font), which is based off of Scheherazade.)

Thank you 🌹

**Comment by LornaSIL** [comment]
Thanks for your feedback. We will add this to our issues for a future version of Scheherazade New. Since we just released a new version I'm not sure we will do this very quickly though.

**Comment by LornaSIL** [comment]
This has been implemented in the new v4.000 release.

**Comment by mr-islam** [comment]
Thank you!

**Comment by jeffheath-sil** [comment]
Not everyone in the Arabic script world is happy with the curved quotation marks. See the discussion here: https://community.software.sil.org/t/scheherazade-new-double-angle-quotation-marks-are-round/9765. If it would be possible to make the angle quotation marks a feature in the font, that would be helpful.

**Comment by LornaSIL** [comment]
@jeffheath-sil We have implemented it as a feature. We hope to do v4.400 around the time Unicode 17.0 is released.
