### ISSUE TITLE
Alternates for bismillah character

### ISSUE THREAD

**Issue by amarz45** [silnrsi/font-scheherazade#8]
I would like a bismillah character (`U+FDFD`) that is nice and big so that it looks good when coming at the beginning of every surah in the Quran. The two bismillah glyphs in this typeface seem a bit small, so it would be nice if there was an alternate that is bigger, intended to go before the surahs in the Quran. The following image shows the difference between this font and Kitab, a fork of this font.

![import-2023-05-11_20:58:33](https://github.com/silnrsi/font-scheherazade/assets/92645199/b87fa6cc-ec4b-4e39-b288-b93331a71aa9)

Additionally, can you add another alternate for surahs 95 and 97 where the bismillah should have a shadda above the bah?

![import-2023-05-11_21:06:11](https://github.com/silnrsi/font-scheherazade/assets/92645199/4ca7ed80-1c80-4fae-aca8-3d6c559609d0)

**Comment by LornaSIL** [comment]
Thank you for your request. We are glad you like Scheherazade New. I'll add your request to our list of enhancements. However, since we have limited resources, we may not be able to fulfill your request. An alternate solution for you is to "call" the font that does have the correct bismillah.

**Comment by LornaSIL** [comment]
We do not feel we can add these extra variants to Scheherazade New. As I suggested above, you should be able to use another font that does have the style you wish to include at the beginning of each Surah.
