### ISSUE TITLE
Narrow no-break space is wider than thin space

### ISSUE THREAD

**Issue by amarz45** [silnrsi/font-scheherazade#9]
I measured the width of some spaces for this font, and here is what I found:

1. The word space is 0.268555 em wide.
2. The thin space (`U+2009`) is 0.134277 em (half of the width of the word space).
3. The narrow no-break space (`U+202F`) is 0.141602 em wide.

I am surprised to find that the narrow no-break space is slightly wider than the thin space. From my understanding, the narrow no-break space should be the same as the thin space aside from the fact that it is non-breaking.

**Comment by LornaSIL** [comment]
Thanks for your request. Even though this is a reasonable request, we do not feel we should update the widths of the spaces since the font has been so widely used already. It would cause document reflow for too many documents.
